generic:
  nameOverride: dind

  containers:
    docker:
      image:
        repository: docker
        pullPolicy: Always
        tag: dind
      args: [ "--mtu=1450" ]
      ports:
        - containerPort: 2375
      livenessProbe:
        tcpSocket:
          port: 2375
      readinessProbe:
        tcpSocket:
          port: 2375
      securityContext:
        privileged: true
      env:
        - name: "DOCKER_TLS_CERTDIR"
          value: ""
