generic:
  nameOverride: dind

  containers:
    default:
      image:
        repository: docker
        pullPolicy: Always
        tag: 19-dind
      # args: [ "--mtu=1450" ]
      ports:
        - containerPort: 2375
      livenessProbe:
        tcpSocket:
          port: 2375
      readinessProbe:
        tcpSocket:
          port: 2375
      securityContext:
        privileged: true
      env:
        - name: "DOCKER_TLS_CERTDIR"
          value: ""

  services:
    default:
      type: ClusterIP
      port: 2375
